#-------------ADMIN>INFO-------------#
#CODING BY MAHIN HASAN
#SCRIPT ALL>IN>ONE
#FACEBOOK > MAHIN HASAN
#GITHUB > JANO-XD
#-------------SCRIPT>GIFT-------------#
# SCRIPT OPEN SOURCE BY
# ADMIN MAHIN HASAN 
#-------------MAIN>MENU-------------#

#----------------import-------------#
import os
import os
import sys
import time
import requests
import requests,os
#---------[COLOUR>MENU]---------#
RED = '\033[38;5;196m'
WHITE = '\033[1;97m'
GREEN = '\033[1;32m'
YELLOW = '\033[1;33m'
BLUE = '\033[1;34m'
ORANGE = '\033[1;35m'
#---------[CONVERT>LINE]---------#
led=f"\033[38;5;46m•\033[38;5;196m•\033[1;35m•\033[1;34m•\033[1;33m•\033[1;32m•\033[1;97m•\033[38;5;196m•\033[38;5;46m•\033[1;35m•\033[1;34m•\033[1;33m•\033[1;32m•\033[1;97m•\033[38;5;196m•\033[38;5;46m•\033[1;32m•\033[1;35m•\033[1;34m•\033[1;97m•\033[1;33m•\033[38;5;196m•\033[1;35m•\033[1;34m•\033[1;33m•\033[1;32m•\033[1;97m•\033[38;5;196m•\033[38;5;46m•\033[38;5;196m•\033[1;32m•\033[1;97m•\033[1;35m•\033[1;34m•\033[1;33m•\033[38;5;46m•\033[1;97m•"
dot=f'{YELLOW}[{GREEN}•{YELLOW}]{WHITE}'
dot2=f'{YELLOW}[{GREEN}√{YELLOW}]{WHITE}'
ys=f'{YELLOW}[{GREEN}y{WHITE}/{RED}n{YELLOW}]'
#--------------------[clear]-----------------#
def clear():
	os.system('clear')
#------------[LOGO>MENU]-----------#
def logo():
	os.system('clear')
	print(f"""
      \033[1;36m╔═╗ ╦═╗ ╔═╗ ╔═╗ ╦╔═ \033[1;31m• \033[1;92m4
      \033[1;36m║   ╠╦╝ ╠═╣ ║   ╠╩╗ \033[1;34m• \033[1;92m0
      \033[1;36m╚═╝ ╩╚═ ╩ ╩ ╚═╝ ╩ ╩ \033[1;35m• \033[1;92m4
  \033[1;92m┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
  ┃\033[1;34m[\033[1;92m❯\033[1;34m] \033[1;97mOWNER     \033[1;31m:  \033[1;92mJAHID       \033[1;92m┃
  ┃\033[1;34m[\033[1;92m❯\033[1;34m] \033[1;97mFACEBOOK  \033[1;31m:  \033[1;91mJAHID HASAN \033[1;92m┃
  ┃\033[1;34m[\033[1;92m❯\033[1;34m] \033[1;97mTOOLS     \033[1;31m:  \033[1;34mAll IN ONE  \033[1;92m┃
  ┃\033[1;34m[\033[1;92m❯\033[1;34m] \033[1;97mTOOLS     \033[1;31m:  \033[38;5;208mV1.0        \033[38;5;46m┃
  ┃\033[1;34m[\033[1;92m❯\033[1;34m] \033[1;97mSTATUS    \033[1;31m:  \033[1;93mFREE        \033[38;5;46m┃
  \033[1;92m┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛""")
 
def mainx():
	logo()
	print(led)
	print(f'    \033[1;92mTHANKS EVERYONE FOR 5K MEMBER ')
	print(led)
	print(f'{YELLOW}[{GREEN}01{YELLOW}]{GREEN} RANDOM CLONE {YELLOW}[{GREEN}T1{YELLOW}]')
	print(f'{YELLOW}[{GREEN}02{YELLOW}]{BLUE} RANDOM CLONE {YELLOW}[{GREEN}T2{YELLOW}]')
	print(f'{YELLOW}[{GREEN}03{YELLOW}]{RED} OLD ID CLONE ')
	print(f'{YELLOW}[{GREEN}04{YELLOW}]{YELLOW} AUTO SHARE ')
	print(f'{YELLOW}[{GREEN}05{YELLOW}]{ORANGE} SMS BOMBING ')
	print(f'{YELLOW}[{GREEN}06{YELLOW}]{GREEN} FILE CREATE ')
	print(f'{YELLOW}[{GREEN}07{YELLOW}]{RED} COOKIE+ APK ')
	print(f'{YELLOW}[{GREEN}08{YELLOW}]{YELLOW} GF & BF HACK ')
	print(f'{YELLOW}[{GREEN}09{YELLOW}]{BLUE} HIDE YOUR SCRIPT ')
	print(f'{YELLOW}[{GREEN}10{YELLOW}]{ORANGE} OPEN SOURCE SCRIPT')
	print(f'{YELLOW}[{RED}00{YELLOW}]{WHITE} EXIT ')
	print(led)
	mahin = input(f'{YELLOW}[{GREEN}??{YELLOW}]{WHITE} SELECT MENU \033[1;91m:\033[1;92m ')
	if mahin in ["1","01"]:
		os.system('rm -rf CHILL-4K && git clone https://github.com/JANO-XD/CHILL-4K && cd CHILL-4K && python run.py ')
	elif mahin in ["2","02"]:
		os.system('rm -rf MAHIN-143 && git clone https://github.com/JANO-XD/MAHIN-143 && cd MAHIN-143 && python run.py ')
	elif mahin in ["3","03"]:
		os.system('rm -rf OLD_CLONE && git clone https://github.com/JANO-XD/OLD_CLONE && cd OLD_CLONE && oldenc.py')
	elif mahin in ["4","04"]:
		os.system('rm -rf AUTO-SHARE && git clone https://github.com/JANO-XD/AUTO-SHARE && cd AUTO-SHARE && python share.py ')
	elif mahin in ["5","05"]:
		os.system('rm -rf SMS_BOMBING && git clone https://github.com/JANO-XD/SMS_BOMBING && cd SMS_BOMBING && python bombing.py')
	elif mahin in ["6","06"]:
		c()
	elif mahin in ["7","07"]:
		os.system('xdg-open https://mega.nz/file/TcIxRTRI#OgYuudVZw5xETi7kfQy4il845fVSzw9Ez5AOR3w_gZI');mainx()
	elif mahin in ["8","08"]:
		os.system('rm -rf GF-HACK &&  git clone https://github.com/JANO-XD/GF-HACK && cd GF-HACK && python gf_bf.py')
	elif mahin in ["9","09"]:
		os.system('rm -rf Encrypte-Script && git clone https://github.com/JANO-XD/Encrypte-Script && cd Encrypte-Script && python encode.py')
	elif mahin in ["10","10"]:
		os.system('xdg-open https://github.com/JANO-XD/OPEN-SOURCE-');mainx()
	elif mahin in ["0","00"]:
		print(f'{dot} {RED}Exit {WHITE}Successful \n{dot} Thanks For Use My  ');os.system("xdg-open https://github.com/JANO-XD");exit()
	else:
		print(f"{dot} {WHITE}Don't Select Wrong Options {RED}!")
		

def c():
	print(led)
	print(f'{YELLOW}[{GREEN}1{YELLOW}]{GREEN} FILE CREATE {YELLOW}[{GREEN} NEED COOKIE  {YELLOW}]')
	print(f'{YELLOW}[{GREEN}2{YELLOW}]{RED} FILE CREATE {YELLOW}[{GREEN}WITHOUT COOKIE{YELLOW}]')
	print(f'{YELLOW}[{GREEN}0{YELLOW}]{WHITE} BACK MENU ')
	print(led)
	ck = input(f'{YELLOW}[{GREEN}?{YELLOW}]{WHITE} CHOOSE \033[1;91m:\033[1;92m ')
	if ck in ["1","01"]:
		os.system('rm -rf FILE-MAKE && git clone https://github.com/JANO-XD/FILE-MAKE && cd FILE-MAKE && python FILE.py ')
	elif ck in ["2","02"]:
		os.system('rm -rf AUTO-FILE && git clone https://github.com/JANO-XD/AUTO-FILE && cd AUTO-FILE && python FILE.py')
	elif ck in ["0","00"]:
		mainx()


mainx()
